name: Docker images building and pushing
on:
  push:
    branches:
      - add_docker-build-to-stage

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta for k6 executor
        id: meta_k6_executor
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/testkube-k6-executor
          tags: |
            type=sha

      - name: Build k6 Executor
        uses: docker/bake-action@v1
        with:
          files: |
            build/agent/docker-bake.hcl
            ${{ steps.meta_k6_executor.outputs.bake-file }}
          targets: build
          push: true

      - name: Output commit sha
        id: github_sha
        run: |
          echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      #Trigger Helm repo workflow to deploy Dashboard to Stage cluster
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
          repository: kubeshop/helm-charts
          event-type: trigger-workflow-executor
          client-payload: '{"image_tag_executor": "sha-${{ steps.github_sha.outputs.sha_short }}", "executor_name": "k6"}'

