name: Code build and checks

on:
  push:
    # build all branches for now
    # alternatively we could do '!main'
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Install k6
        run: make install-k6-ci

      - name: Test
        run: go test -v ./...
